apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: ghcr.io/advplyr/audiobookshelf:latest
        name: audiobookshelf
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: audiobook-configmap
                key: port
        resources: {}
        volumeMounts:
          - mountPath: /config
            name: abs-config-pvc 
          - mountPath: /metadata
            name: abs-metadata-pvc
          - mountPath: /audiobooks
            name: abs-audiobooks-pvc
          - mountPath: /podcasts
            name: abs-podcasts-pvc
      volumes:
        - name: abs-config-pvc
          persistentVolumeClaim:
            claimName: abs-config-pvc
        - name: abs-metadata-pvc
          persistentVolumeClaim:
            claimName: abs-metadata-pvc
        - name: abs-audiobooks-pvc
          persistentVolumeClaim:
            claimName: abs-audiobooks-pvc
        - name: abs-podcasts-pvc
          persistentVolumeClaim:
            claimName: abs-podcasts-pvc
status: {}
