apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: audiobookshelf
    spec:
      containers:
      - image: ghcr.io/advplyr/audiobookshelf:latest
        name: audiobookshelf
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: audiobook-configmap
                key: port
        resources: {}
        volumeMounts:
          - mountPath: /etc/abs/config
            name: abs-config-pvc 
          - mountPath: /etc/abs/metadata
            name: abs-metadata
          - mountPath: /etc/abs/audiobooks
            name: abs-audiobooks
          - mountPath: /etc/abs/podcasts
            name: abs-podcasts
      volumes:
        - name: abs-config
          persistentVolumeClaim:
            claimName: abs-config-pvc
        - name: abs-metadata
          persistentVolumeClaim:
            claimName: abs-metadata-pvc
        - name: abs-audiobooks
          persistentVolumeClaim:
            claimName: abs-audiobooks-pvc
        - name: abs-podcasts
          persistentVolumeClaim:
            claimName: abs-podcasts-pvc
status: {}
